config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: [:registrations], controllers: {
    sessions: 'admins/sessions'
  }

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  get 'home/index'
  root 'orders#index'

  resources :orders, except: [:show, :destroy] do
    member do
      get :cancel
      get :make
      get :done
      get :close
      get :reopen
    end
  end

  get 'kitchen', to: 'orders#kitchen'
  get 'report', to: 'orders#report'

  resources :work_shifts, except: [:show, :destroy] do
    member do
      get :close
      get :reopen
    end
  end

  resources :restaurants, except: [:show, :destroy] do
    member do
      get :activate
      get :deactivate
    end
  end

  resources :products, except: [:show, :destroy] do
    member do
      get :activate
      get :deactivate
    end
  end

  resources :categories, except: [:show, :destroy] do
    member do
      get :activate
      get :deactivate
      get :seeing_in_kitchen
    end
  end

  namespace :admins do
    resources :users, only: [:edit, :update]
    resources :admins, only: [:edit, :update]
  end

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :work_shift
  has_many :order_products
  has_many :products, through: :order_products

  # TODO: colocar condições do proc em um método
  accepts_nested_attributes_for :order_products, allow_destroy: true, reject_if: proc { |obj| OrderProduct.find_by_id(obj[:id].to_i).nil? && obj[:quantity].to_i == 0 }

  validates :table, :status, :work_shift, presence: true
  validates :order_products, length: { minimum: 1, too_short: "mínimo %{count} item" }

  default_scope { order(created_at: :asc, updated_at: :asc) }
  scope :to_the, ->(work_shift_id) { where(work_shift_id: work_shift_id) }
  scope :registered, -> { where(status: 'registered') }
  scope :closed, -> { where(status: 'closed') }
  scope :canceled, -> { where(status: 'canceled') }
  scope :kitchen, -> { joins(:products)
                       .joins("INNER JOIN categories ON products.category_id = categories.id")
                       .where(categories: {see_in_kitchen: true}).uniq }
  scope :for_make, -> { joins(:order_products)
                        .where("(order_products.quantity - order_products.making - order_products.done) != 0").uniq }
  scope :making, -> { joins(:order_products)
                      .where("order_products.making != 0").uniq }
  scope :done, -> { joins(:order_products)
                    .where("order_products.done != 0").uniq }


  def reopen!
    update_attributes({ status: 'registered' })
  end

  def close!
    update_attributes({ status: 'closed' })
  end

  def cancel!
    update_attributes({ status: 'canceled' })
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :cancel, :make, :done, :close, :reopen]
  before_action :load_products, only: [:new, :edit, :update, :create]
  before_action :load_tables, only: [:new, :edit, :update, :create]
  before_action :load_categories, only: [:new, :edit, :update, :create]
  before_action :load_domains, only: [:index, :kitchen, :report]
  before_action :authenticate_user!

  def index
    # @orders = filter_orders.includes([:work_shift, :products])
    @orders = filter_orders.to_the(current_work_shift.try(:id)).page(params[:page]).per(20)
  end

  def show
  end

  def new
    @order = Order.new

    @products.each do |product|
      @order.order_products.build(product_id: product.id)
    end
  end

  def edit
    @products.select { |product| !@order.products.include?(product) }.each do |product|
      @order.order_products.build(product_id: product.id)
    end
  end

  def create
    @order = Order.new(order_params)

    @order.status = "registered"
    @order.work_shift_id = current_work_shift.id

    respond_to do |format|
      if @order.save
        format.html { redirect_to orders_path, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    params[:order].delete(:status)
    params[:order].delete(:work_shift_id)

    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to orders_path, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    # @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def make
    @order.order_products.each { |order_product| order_product.make! }

    respond_to do |format|
      format.html { redirect_to kitchen_path, notice: 'Order was successfully making.' }
      format.json { render :show, status: :ok, location: @order }
    end
  end

  def done
    @order.order_products.each { |order_product| order_product.done! }

    respond_to do |format|
      format.html { redirect_to kitchen_path, notice: 'Order was successfully done.' }
      format.json { render :show, status: :ok, location: @order }
    end
  end

  def reopen
    @order.reopen!
    respond_to do |format|
      format.html { redirect_to orders_path, notice: 'Order was successfully reopened.' }
      format.json { render :show, status: :ok, location: @order }
    end
  end

  def close
    @order.close!
    respond_to do |format|
      format.html { redirect_to orders_path, notice: 'Order was successfully closed.' }
      format.json { render :show, status: :ok, location: @order }
    end
  end

  def cancel
    @order.cancel!
    respond_to do |format|
      format.html { redirect_to orders_path, notice: 'Order was successfully canceled.' }
      format.json { render :show, status: :ok, location: @order }
    end
  end

  def kitchen
    @orders = filter_orders.to_the(current_work_shift.try(:id)).registered.kitchen
  end

  def report
    # @orders = filter_orders.includes([:work_shift, :products])
    @orders = filter_orders
    @dash_orders = @orders
    @orders = @orders.page(params[:page]).per(20)
  end

  private

    def load_domains
      @domains = {}
      @domains[:tables] = load_tables.map { |table| [table, table] }
      @domains[:products] = load_products.map { |product| [product.name, product.id] }
      @domains[:work_shifts] = load_work_shift_names.map { |work_shift| [work_shift, work_shift] }
      @domains[:statuses] = [['Registered', 'registered'], ['Closed','closed'], ['Canceled', 'canceled']]

      # @domains[:statuses] = [Order.unscope(:order).select(:status).order(status: :desc).uniq]
    end

    def load_products
      @products = Product.to_the(current_restaurant.try(:id)).active.default_order
    end

    def load_categories
      @categories = Product.to_the(current_restaurant.try(:id))
                           .joins(:category).select("categories.id, categories.name")
                           .where(categories: { active: true }).where(products: { active: true })
                           .uniq.order("categories.name")
    end

    # TODO: retornar um hash com ID e name
    def load_tables
      @tables = []
      # (1..40).each do |n|
      #   @tables << {
      #     id: n,
      #     name: "Table #{sprintf('%02d', n)}"
      #   }
      # end
      (1..40).each {|n| @tables << "Table #{sprintf('%02d', n)}"}
      @tables
    end

    def load_work_shift_names
      names = []
      (1..2).each {|t| names << "Work Shift #{sprintf('%02d', t)}"}
      names
    end

    def current_orders
      Order.joins(:work_shift).where(work_shifts: { restaurant_id: current_restaurant.try(:id) })
    end

    def filter_orders
      finder = OrdersFinder.new(
        params: order_find_params,
        init_collection: current_orders
      )

      finder.execute
    end

    def order_find_params
      filters = params.to_hash
      filters = filters.except('access_token', 'action', 'controller')
      filters
    end

    def set_order
      @order = Order.find(params[:id])
    end

    def order_params
      params.require(:order).permit(:table, :status, :work_shift_id,
        order_products_attributes: [:id, :quantity, :note, :product_id])
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/report/_dashboard.html.erb
<div class="row justify-content-md-center g-4 mb-5">
  <% orders = @dash_orders.unscope(:order).select("orders.status, count(orders.id)").group(:status).order(status: :desc).uniq %>
  <% total = @dash_orders.count %>

  <div class="col-sm-auto">
    <ul class="list-group list-group-horizontal">
      <li class="list-group-item text-center">
        <h5 class="mb-1"><%= total %></h5>
        <small>Total</small>
      </li>
      <li class="list-group-item text-center">
        <h5 class="mb-1"><i class="bi bi-bar-chart-fill"></i></h5>
        <small>100%</small>
      </li>
    </ul>
  </div>

  <% orders.each do |order| %>
    <div class="col-sm-auto">
      <ul class="list-group list-group-horizontal">
        <li class="list-group-item text-center">
          <h5 class="mb-1"><%= order.count %></h5>
          <small><%= order.status.humanize %></small>
        </li>
        <li class="list-group-item text-center">
          <h5 class="mb-1"><i class="bi bi-bar-chart-fill"></i></h5>
          <small><%= order.count*100/total %>%</small>
        </li>
      </ul>
    </div>
  <% end %>
</div>

<!-- Gráfico de linha sobre faturamento no mês -->
<div class="row mb-5">
  <%
    billing = @dash_orders.unscope(:order).group_by_day(:created_at).count

    values = @dash_orders.unscope(:order)
                         .select("DATE(orders.created_at) AS date, sum(products.price_cents*order_products.quantity) as price_cents")
                         .joins(:products)
                         .where("orders.status != 'canceled'")
                         .group("orders.created_at")
  
    values_hash = {}
    values.each { |order| values_hash[order.date] = humanized_money Money.new(order.price_cents, Product.new.price.currency.iso_code) }

    billing.each do |k, v|
      if values_hash.keys.include?(k)
        billing[k] = values_hash[k]
      else
        billing[k] = 0
      end
    end

    series = [{ name: "Billing", data: billing }]
  %>
​ <% options = {
      title: 'Billing per Day',
      xtitle: 'Days',
      ytitle: 'Amount (€)',
      dataLabels: {
        enabled: false
      },
      stroke: {
        curve: 'smooth',
      }
    } %>
​
  <%= area_chart(series, options) %>
</div>

<!-- Gráfico de barra sobre quantidade de pedidos por hora -->
<div class="row mb-5">
  <%
    orders = @dash_orders.unscope(:order).where("orders.status != 'canceled'").group_by_hour_of_day(:created_at).count

    series = [{ name: "Orders", data: orders }]
    options = {
      title: 'Orders per Hour',
      xtitle: 'Hours',
      ytitle: 'Quantity'
    }
  %>
​
  <%= column_chart(series, options) %>
</div>

<!-- Gráficos de pizza sobre quantidade de produtos vendidos -->
<div class="row justify-content-evenly g-2">
  <div class="col-lg-5">
    <% datas = @dash_orders.unscope(:order)
                      .select("products.name, count(products.id)")
                      .joins(:products)
                      .joins("INNER JOIN categories ON products.category_id = categories.id")
                      .where(categories: { active: true }).where(products: { active: true })
                      .group("products.id").order("products.name")
    series = []
    series = datas.map { |data| series << { name: data.name, data: data.count } }
    options = {
      title: 'Products',
      legend: 'left'
    } %>
    ​
    <%= pie_chart(series[0], options) %>
  </div>
  <div class="col-lg-5">
    <% datas = @dash_orders.unscope(:order)
                      .select("categories.name, count(categories.id)")
                      .joins(:products)
                      .joins("INNER JOIN categories ON products.category_id = categories.id")
                      .where(categories: { active: true }).where(products: { active: true })
                      .group("categories.id").order("categories.name")
    series = []
    series = datas.map { |data| series << { name: data.name, data: data.count } }
    options = {
      title: 'Categories',
      legend: 'left',
      markers: {
        size: 3
      }
    } %>
    ​
    <%= pie_chart(series[0], options) %>
  </div>
</div>

app/views/orders/report/_orders.html.erb
<% statuses = ['registered', 'closed', 'canceled'] %>

<% statuses.each do |status| %>
  <% 
    muted = 'text-muted' if status == 'canceled'

    case status
    when 'registered'
      bg_style = 'style=background-color:#6dd47e;color:#293250'
      btn_style = 'background-color:#293250'
    when 'closed'
      bg_style = 'style=background-color:#ffa781;color:#5b0e2d'
      btn_style = 'background-color:#5b0e2d'
    else
      bg_style = ''
      btn_style = 'display:none'
    end
  %>

  <div class="accordion mb-3" id="accordionFlushOrders">
    <% @orders.send("#{status.to_s}").each do |order| %>
      <div class="accordion-item">
        <h2 class="accordion-header" id="heading<%= order.id %>">
          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" <%= bg_style %>
                  data-bs-target="#collapse<%= order.id %>" aria-expanded="false" aria-controls="collapse<%= order.id %>">
            <div class="row d-flex align-items-start me-2 w-100">
              <div class="col-md-10">
                <h5 class="fw-bold mb-2 <%= muted %>">Order #<%= order.id %></h5>

                <% total = 0 %>
                <% order.order_products.each {|op| total += op.product.price*op.quantity } %>
                <p class="m-0 <%= muted %>"><%= order.table %>, <%= order.status.humanize %>, Total: <%= currency_symbol %><%= total %></p>
              </div>

              <div class="col-md-2 text-end mt-2">
                <% if params[:action] == 'report' %>
                  <p><%= I18n.l(order.created_at, format: I18n.t('time.formats.separate_bar')) %></p>
                <% else %>

                  <%= link_to edit_order_path(order), { class: 'btn btn-sm text-white', style: "#{btn_style}", title: 'Edit' } do %>
                    <i class='bi bi-pencil'></i>
                  <% end %>
                  <% if order.status != 'closed' && order.status != 'canceled' %>
                    <%= link_to close_order_path(order), { class: 'btn btn-sm text-white', style: "#{btn_style}", title: 'Close',
                        data: { confirm: 'Are you sure?' } } do %>
                      <i class='bi bi-check'></i>
                    <% end %>
                    <%= link_to cancel_order_path(order), { class: 'btn btn-sm text-white', style: "#{btn_style}", title: 'Cancel',
                        data: { confirm: 'It cannot be undone. Are you sure?' } } do %>
                      <i class='bi bi-trash'></i>
                    <% end %>
                  <% elsif order.status == 'closed' %>
                    <%= link_to reopen_order_path(order), { class: 'btn btn-sm text-white', style: "#{btn_style}", title: 'Reopen',
                        data: { confirm: 'Are you sure?' } } do %>
                      <i class='bi bi-recycle'></i>
                    <% end %>
                  <% end %>

                <% end %>
              </div>
            </div>
          </button>
        </h2>
        <div id="collapse<%= order.id %>" class="accordion-collapse collapse" aria-labelledby="heading<%= order.id %>"
            data-bs-parent="#accordionFlushOrders">
          <div class="accordion-body" <%= bg_style %>>
            <ul class="list-group">
              <% order.order_products.each do |order_product| %>
                <li class="list-group-item d-flex justify-content-between align-items-start" <%= bg_style %>>
                  <div class="ms-2 me-3 w-100 <%= muted %>">
                    <div class="fw-bold me-1">
                      <%= order_product.product.name %> - <%= humanized_money_with_symbol order_product.product.price %>
                    </div>
                    <%= order_product.note %>
                  </div>
                  <span style="<%= btn_style %>" class="badge rounded-pill"><%= order_product.quantity %></span>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

<div class="row mt-4">
  <div class="col">
    <%= paginate(@orders) %>
  </div>
</div>