config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: [:registrations], controllers: {
    sessions: 'admins/sessions'
  }

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  get 'home/index'
  root 'orders#index'

  resources :orders, except: [:show, :destroy] do
    member do
      get :cancel
      get :make
      get :done
      get :close
      get :reopen
    end
  end

  get 'kitchen', to: 'orders#kitchen'
  get 'report', to: 'orders#report'

  resources :work_shifts, except: [:show, :destroy] do
    member do
      get :close
      get :reopen
    end
  end

  resources :restaurants, except: [:show, :destroy] do
    member do
      get :activate
      get :deactivate
    end
  end

  resources :products, except: [:show, :destroy] do
    member do
      get :activate
      get :deactivate
    end
  end

  resources :categories, except: [:show, :destroy] do
    member do
      get :activate
      get :deactivate
      get :seeing_in_kitchen
    end
  end

  namespace :admins do
    resources :users, only: [:edit, :update]
    resources :admins, only: [:edit, :update]
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products

  before_save :name_humanize

  validates :name, presence: true

  scope :to_the, ->(restaurant_id) { where(restaurant_id: restaurant_id) }
  scope :active, -> { where(active: true) }
  scope :deactivate, -> { where(active: false) }
  scope :see_in_kitchen, -> { where(see_in_kitchen: true) }

  def name_humanize
    self.name = self.name.humanize.titleize
  end

  def activate!
    update_attributes({ active: true })
  end

  def deactivate!
    update_attributes({ active: false })
  end

  def seeing_in_kitchen!(value)
    update_attributes({ see_in_kitchen: value })
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :activate, :deactivate, :seeing_in_kitchen]

  before_action :authenticate_user!

  def index
    @categories = Category.to_the(current_restaurant.try(:id)).order(:name)
  end

  def show
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)

    @category.restaurant_id = current_restaurant.try(:id)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_path, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def activate
    @category.activate!
    respond_to do |format|
      format.html { redirect_to categories_path, notice: 'Category was successfully activated.' }
      format.json { render :show, status: :ok, location: @category }
    end
  end

  def deactivate
    @category.deactivate!
    respond_to do |format|
      format.html { redirect_to categories_path, notice: 'Category was successfully disabled.' }
      format.json { render :show, status: :ok, location: @category }
    end
  end

  def seeing_in_kitchen
    @category.seeing_in_kitchen!(!@category.see_in_kitchen)
    respond_to do |format|
      format.html { redirect_to categories_path, notice: 'Category was successfully updated.' }
      format.json { render :show, status: :ok, location: @category }
    end
  end

  private

    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name, :active, :see_in_kitchen)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-8 mb-3">
      <%= f.label :name, { class: 'form-label' } %>
      <%= f.text_field :name, { class: 'form-control' } %>
    </div>
    <div class="col-md-4 align-self-end mb-3 pb-1">
      <div class="form-check form-switch">
        <%= f.label :see_in_kitchen, { class: 'form-check-label' } %>
        <%= f.check_box :see_in_kitchen, { class: 'form-check-input' } %>
      </div>
    </div>
  </div>
  <div class="actions">
    <%= f.submit "#{params[:action].humanize} #{@category.class.to_s.humanize}", { class: 'btn btn-primary mb-3' } %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class='row justify-content-center'>
  <div class='col-md-6 col-lg-7'>
    <h4 class="mb-3">Editing Category</h4>
    <%= render 'form' %>
  </div>
</div>

app/views/categories/index.html.erb
<div class='row justify-content-center'>
  <div class='col-md-9 col-lg-10'>
    <% if notice %>
      <div class="alert alert-success alert-dismissible fade show p-2" role="alert">
        <p id="notice" class="m-1"><%= notice %></p>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close" style="padding: 1rem 1rem !important"></button>
      </div>
    <% end %>

    <div class='table-responsive'>
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Name</th>
            <th colspan='3' style='width:12%'>Actions</th>
          </tr>
        </thead>

        <tbody>
          <% if @categories.active.count > 0 %>

            <% @categories.active.each do |category| %>
              <tr>
                <td><%= category.name %></td>
                <td>
                  <%= link_to edit_category_path(category), { class: 'btn btn-sm btn-secondary', title: 'Edit' } do %>
                    <i class='bi bi-pencil'></i>
                  <% end %>
                </td>
                <td>
                  <% if category.see_in_kitchen %>
                    <%= link_to seeing_in_kitchen_category_path(category), { class: 'btn btn-sm btn-secondary',
                        title: 'Don\'t See in kitchen', data: { confirm: 'Are you sure?' } } do %>
                        <i class='bi bi-eye-slash'></i>
                    <% end %>
                  <% else %>
                    <%= link_to seeing_in_kitchen_category_path(category), { class: 'btn btn-sm btn-secondary',
                        title: 'See in kitchen', data: { confirm: 'Are you sure?' } } do %>
                        <i class='bi bi-eye'></i>
                    <% end %>
                  <% end %>
                </td>
                <td>
                  <%= link_to deactivate_category_path(category), { class: 'btn btn-sm btn-danger', title: 'Deactivate',
                      data: { confirm: 'Disabling the category will cause your products to be disabled as well. Are you sure?' } } do %>
                    <i class='bi bi-trash'></i>
                  <% end %>
                </td>
              </tr>
            <% end %>

            <% @categories.deactivate.each do |category| %>
              <tr class='text-muted'>
                <td><%= category.name %></td>
                <td>
                  <%= link_to edit_category_path(category), { class: 'btn btn-sm btn-secondary', title: 'Edit' } do %>
                    <i class='bi bi-pencil'></i>
                  <% end %>
                </td>
                <td>
                  <% if category.see_in_kitchen %>
                    <%= link_to seeing_in_kitchen_category_path(category), { class: 'btn btn-sm btn-secondary',
                        title: 'Don\'t See in kitchen', data: { confirm: 'Are you sure?' } } do %>
                        <i class='bi bi-eye-slash'></i>
                    <% end %>
                  <% else %>
                    <%= link_to seeing_in_kitchen_category_path(category), { class: 'btn btn-sm btn-secondary',
                        title: 'See in kitchen', data: { confirm: 'Are you sure?' } } do %>
                        <i class='bi bi-eye'></i>
                    <% end %>
                  <% end %>
                </td>
                <td>
                  <%= link_to activate_category_path(category), { class: 'btn btn-sm btn-danger', title: 'Activate',
                      data: { confirm: "Reactivating the category will cause your products to be reactivated as well. Are you sure?" } } do %>
                    <i class='bi bi-recycle'></i>
                  <% end %>
                </td>
              </tr>
            <% end %>

          <% else %>
            <tr><td colspan="5" class="text-center text-muted">
              No records were found. You can register if you want...
            </td></tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/categories/new.html.erb
<div class='row justify-content-center'>
  <div class='col-md-6 col-lg-7'>
    <h4 class="mb-3">New Category</h4>
    <%= render 'form' %>
  </div>
</div>