config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: [:registrations], controllers: {
    sessions: 'admins/sessions'
  }

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  get 'home/index'
  root 'orders#index'

  resources :orders, except: [:show, :destroy] do
    member do
      get :cancel
      get :make
      get :done
      get :close
      get :reopen
    end
  end

  get 'kitchen', to: 'orders#kitchen'
  get 'report', to: 'orders#report'

  resources :work_shifts, except: [:show, :destroy] do
    member do
      get :close
      get :reopen
    end
  end

  resources :restaurants, except: [:show, :destroy] do
    member do
      get :activate
      get :deactivate
    end
  end

  resources :products, except: [:show, :destroy] do
    member do
      get :activate
      get :deactivate
    end
  end

  resources :categories, except: [:show, :destroy] do
    member do
      get :activate
      get :deactivate
      get :seeing_in_kitchen
    end
  end

  namespace :admins do
    resources :users, only: [:edit, :update]
    resources :admins, only: [:edit, :update]
  end

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OrderingSystem</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <%= stylesheet_link_tag    'admins', media: 'all', 'data-turbolinks-track' => true %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
  <%= csrf_meta_tags %>

  <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
  </style>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OrderingSystem</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <!-- Bootstrap CSS v5.1.0-->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
  <!-- Bootstrap JS -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
  <!-- Bootstrap Icons 1.4.0-->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
  <%= csrf_meta_tags %>
</head>
<body class='bg-light>'>
  <header>
    <div class="collapse bg-dark" id="navbarHeader">
      <div class="container">
        <div class="row">
          <div class="col-sm-8 col-md-7 py-4">
            <% if admin_signed_in? %>
              <h4 class="text-white"><%= link_to 'Hello', restaurants_path, { class: 'text-white header-link' } %></h4>
              <p class="text-muted"><%= current_admin.email %></p>
            <% elsif user_signed_in? %>
              <h4 class="text-white"><%= link_to 'Hello', orders_path, { class: 'text-white header-link' } %></h4>
              <p class="text-muted">
                <%= current_user.restaurant.name %><br>
                <% if has_open_work_shift? %>
                  <%= current_work_shift.name %> it's open<br>
                <% else %>
                  No work shifts currently open<br>
                <% end %>
              </p>
            <% end %>
          </div>
          <div class="col-sm-4 offset-md-1 py-4">
            <ul class="list-unstyled">
              <% if admin_signed_in? %>
                <%= link_to 'Edit Account', edit_admins_admin_path(current_admin), { class: "text-white header-link" } %><br>
                <%= link_to 'Log out', destroy_admin_session_path, { method: :delete, class: "text-white header-link" } %>
              <% elsif user_signed_in? %>
                <div class="row">
                  <div class="col">
                    <%= link_to 'New Order', new_order_path, { class: "text-white header-link" } %><br>
                    <%= link_to 'Kitchen', kitchen_path, { class: "text-white header-link" } %><br>
                  </div>
                  <div class="col">
                    <%= link_to 'Work Shifts', work_shifts_path, { class: "text-white header-link" } %><br>
                    <%= link_to 'Products', products_path, { class: "text-white header-link" } %><br>
                    <%= link_to 'Categories', categories_path, { class: "text-white header-link" } %>
                  </div>
                  <div class="col">
                    <%= link_to 'Report', report_path, { class: "text-white header-link" } %><br>
                    <%= link_to 'Edit Account', edit_user_registration_path, { class: "text-white header-link" } %><br>
                    <%= link_to 'Log out', destroy_user_session_path, { class: "text-white header-link", method: :delete } %><br>
                  </div>
                </div>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="navbar navbar-dark bg-dark shadow-sm">
      <div class="container">
        <div class="navbar-brand d-flex align-items-center">
          <i class="bi bi-geo me-2" ></i>
          <!-- <strong><%= params[:controller] %></strong> -->
          <strong><%= "Restaurant" if user_signed_in? %></strong>
          <strong><%= "Admin" if admin_signed_in? %></strong>
        </div>
        <div class="navbar-text d-flex ms-auto me-3">

          <% case params[:controller]
          when 'work_shifts'
            if has_open_work_shift? %>
              <%= link_to 'Open Work shift', work_shifts_path, { method: :post, class: "btn btn-outline-secondary btn-sm", data:
                  ( @work_shifts.current_work_shift(current_user.id).nil? ? nil :
                  { confirm: 'There is an open work shift, you need to close it first.' } ) } %>
            <% else %>
              <%= link_to 'Open Work shift', work_shifts_path, { method: :post, class: "btn btn-outline-secondary btn-sm" } %>
            <% end %>
          <% when 'restaurants' %>
             <%= link_to 'New Restaurant', new_user_registration_path, { class: "btn btn-outline-secondary btn-sm" } %>
          <% when 'orders', 'products', 'categories'
            base = "#{params[:controller].singularize}" %>
            <%= link_to "New #{base}", send("new_#{base}_path"), { class: "btn btn-outline-secondary btn-sm" } %>
          <% end %>

        </div>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader"
                aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
          <i class="bi bi-list"></i>
        </button>
      </div>
    </div>
  </header>

  <div class="container py-5">
    <%= yield %>
  </div>

</body>
</html>

app/views/layouts/user.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OrderingSystem</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <%= stylesheet_link_tag    'users', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
  <%= csrf_meta_tags %>

  <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
  </style>
</head>
<body>

<%= yield %>

</body>
</html>